version: "3"
services:
  app:
    volumes:
      - ./app:/app
      - ./host/django/settings.development.py:/app/mitaba/core/settings.py
      - ./host/gunicorn/log:/tmp
      - ./host/postgresql/dumpdata:/dumpdata
