version: '3'

services:
  db:
    image: postgres
  mitaba:
    build: .
    command: python3 manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    environment:
      - DJ_ENV
      - SECRET_KEY
      - ALLOWED_HOSTS
    depends_on:
      - db