#%RAML 1.0
title: Netuleny
version: v2
baseUri: https://netuleny.com/api/{version}
mediaType: application/json
types:
  Tag: string
  Url: string
  HTML: string

  Price:
    properties:
      rub: number
      usd?: number
      eur?: number
      cny?: number

  Image:
    properties:
      xs: Url
      sm: Url
      md: Url
      lg: Url
      description?: string

  Schedule:
    properties:
      id: number
      start: datetime

  Seo:
    properties:
      title: string
      description: string

  Style:
    properties:
      id: number
      slug: string
      name: string

  Month:
    properties:
      id: number
      slug: string
      name: string

  Activity:
    properties:
      id: number
      slug: string
      name: string


  Location:
    properties:
      id: number
      slug: string
      name: string
      trips_count?: number
      exclude?: boolean
      show?: boolean
      leaf?: boolean

  Trip:
    properties:
      id: number
      slug: string
      name: string
      images: Image[]
      min_price: Price
      duration: string
      nights?: number
      locations?: Location[]
      main_kinds?: Activity[]
      kinds?: Activity[]
      prices: Price[]
      schedules?: Schedule[]
      tags?: Tag[]
      open_date?: datetime
      description?: HTML
      inclusive?: HTML
      refund?: HTML
      plan?: HTML
      requirements?: HTML

  Collection:
    properties:
      id: number
      slug: string
      name: string
      collection_type: CollectionType
      trips_count: number
      trip: Trip
      leaf: boolean
      show?: boolean
      exclude?: boolean

  CollectionType:
    enum: [ activities, locations, styles, months ]

  CollectionInfo:
    properties:
      /activities|locations|months|styles/: Collection

  HomeCollectionsItem:
    properties:
      limit?: number
      items: Collection[]

  Bookmark:
    properties:
      id: number
      type:
        enum: [ trip, collection, search_result ]
      deleted: boolean
      item: BookmarkItemOfTrip | BookmarkItemOfCollection | BookmarkItemOfSearchResult

  BookmarkItem:
    properties:
      trip: Trip

  BookmarkItemOfTrip:
    type: BookmarkItem

  BookmarkItemOfCollection:
    type: [ BookmarkItem, Collection ]

  BookmarkItemOfSearchResult:
    type: BookmarkItem
    properties:
      filters?:
        properties:
          activities?: Activity[]
          locations?: Location[]
          months?: Month[]
          styles?: Style[]
      q?: string

  Post:
    properties:
      id: number
      slug: string
      name: string
      draft: boolean
      date: datetime
      short_description: string
      author: string
      text: HTML
      images: Image[]
      kinds?: Activity[]
      locations: Location[]
      tags?: Tag[]

  Order:
    properties:
      id: number
      amount: string
      currency: string
      paid_amount: string
      paid_currency: string
      kids: number
      adults: number
      final_price: string
      trip_date: string
      book_date: string
      message: string
      state: string
      url: string
      persons_data: string
      token: string
      netuleny_status: string
      name: string
      email: string
      phone: string
      trip_name: string
      trip_duration: number
      prepayment: string
      prepayment_equal_final: boolean
      trip_id: number
      trip_nights: number
      note: string
      link_payment: string
      order_paid: string

  Currency:
    properties:
      symbol: string
      isBefore: boolean
      currencyCode: string
      active: boolean

  Language:
    properties:
      title: string
      countryCode: string
      languageCode: string
      active: boolean

  Config:
    properties:
      languages: Language[]
      currencies: Currency[]

  Limiting:
    properties:
      limit?: number

  Paging:
    properties:
      limit?: number
      offset?: number

  Filtering:
    properties:
      activities?: string[]
      locations?: string[]
      months?: string[]
      styles?: string[]

  Searching:
    properties:
      q?: string

  Dropdowning:
    properties:
      dropdown?: boolean

  Ordering:
    properties:
      order?: string
      direction?:
        enum: [ asc, dsc ] # TODO INCONSISTENT

  WithCount:
    properties:
      count: number

  WithSeo:
    properties:
      seo: Seo

  WithTrip:
    properties:
      trip: Trip

  WithCollection:
    properties:
      collection: CollectionInfo

resourceTypes:
  TripsResource:
    get:
      description: |
        Список туров
      queryParameters:
        q?: string
        activities?: string[]
        locations?: string[]
        months?: string[]
        styles?: string[]
        limit?: number
        offset?: number
        recommend?: boolean
        order?:
          enum: [ random ]
        price_to?: number
        price_from?: number
      responses:
        200:
          body:
            properties:
              trips: Trip[]
              meta: [ WithCount, WithSeo ]

  TripResource:
    get:
      description: |
        Конкретный тур
      responses:
        200:
          body:
            properties:
              trip: Trip
              meta: [ WithSeo ]

  HomeCollectionsResource:
    get:
      description: |
        Несколько коллекций каждого типа для главной страницы
      queryParameters:
        limit?: number
      responses:
        200:
          body:
            properties:
              collections:
                properties:
                  activities: HomeCollectionsItem
                  locations: HomeCollectionsItem
                  months: HomeCollectionsItem
                  styles: HomeCollectionsItem

  CollectionsResource:
    get:
      description: |
        Список коллекций
      queryParameters:
        q?: string
        limit?: number
        offset?: number
        order?: string
        direction?:
          enum: [ asc, dsc ] # TODO INCONSISTENT
      responses:
        200:
          body:
            properties:
              /activities|locations|months|styles/: Collection[]
              meta: [ WithCount, WithCollection ]

  ListCategoriesResource:
    get:
      description: |
        Списки категорий
      queryParameters:
        q?: string
        dropdown?: boolean
      responses:
        200:
          body:
            properties:
              /groups|activities|locations|months|styles/: (Activity | Location | Month | Style)[]

  PostsResource:
    get:
      description: |
        Список постов
      responses:
        200:
          body:
            properties:
              posts: Post[]
              meta: [ WithCount, WithSeo ]

  PostResource:
    get:
      description: |
        Список постов
      responses:
        200:
          body:
            properties:
              post: Post
              meta: [ WithSeo ]

  ProfileResource:
    get:
      description: |
        Профиль
      responses:
        200:
          body:
            properties:
              auth_type: string
              avatar: Url
              email: string
              name: string

  BookmarksResource:
    get:
      description: |
        Избранное
      responses:
        200:
          body:
            properties:
              bookmarks:
                properties:
                  trips: Bookmark[]
                  collections: Bookmark[]
                  search_results: Bookmark[]
    post:
      body:
        properties:
          bookmark:
            properties:
              id?: number
              slug?: string
              images: Image[]
              type?:
                enum: [ activities, locations, months, styles ]
          type:
            enum: [ trip, collection, search_results ]
      responses:
        200:
          body:
            properties:
              bookmark: Bookmark

  OrderResource:
    get:
      description: |
        Заказ
      responses:
        200:
          body: Order
    put:
      body: Order
      responses:
        200:
          body: object

  ConfigResource:
    get:
      description: |
        Конфиг
      responses:
        200:
          body:
            properties:
              config: Config


/trips:
  description: Список туров, постранично, с поиском
  type: TripsResource
  /{trip}:
    description: Конкретный тур
    type: TripResource
  /count:
    description: Счётчик туров
    get:
      description: |
        Счётчик туров
      queryParameters:
        q?: string
        activities?: string[]
        locations?: string[]
        months?: string[]
        styles?: string[]
        limit?: number
        offset?: number
      responses:
        200:
          body: WithCount

/banner:
  description: Тур-баннер для главной страницы
  get:
    description: |
      Баннер на главной странице
    responses:
      200:
        body: WithTrip

/collections:
  description: Список коллекция для главной страницы
  type: HomeCollectionsResource
  /activities:
    description: Корневая коллекция активностей
    type: CollectionsResource
  /locations:
    description: Корневая коллекция локаций
    type: CollectionsResource
  /months:
    description: Корневая коллекция месяцев
    type: CollectionsResource
  /styles:
    description: Корневая коллекция стилей
    type: CollectionsResource

/groups:
  description: Список главных активностей путешествия
  type: ListCategoriesResource
/months:
  description: Список месяцев
  type: ListCategoriesResource
/styles:
  description: Список стилей путешествия
  type: ListCategoriesResource
/activities:
  description: Список активностей
  type: ListCategoriesResource
  /{activity}:
    description: Коллекция активностей
    type: CollectionsResource
/locations:
  description: Список локаций
  type: ListCategoriesResource
  /{location}:
    description: Коллекция локаций
    type: CollectionsResource

/posts:
  description: Список постов (блог), постранично
  type: PostsResource
  /{post}:
    displayName: Пост
    description: Отдельный пост блога
    type: PostResource

/subscription:
  description: Подписка
  get:
    description: |
      Подписка
    responses:
      200:
        body:
          properties:
            status: string

/sign_in:
  description: Авторизация (вход)
  post:
    queryParameters:
      code: string
      redirect_uri: Url
      type:
        enum: [ fb | vk | incognito ]
    responses:
      200:
        body: object

/sign_out:
  description: Выход
  delete:
    responses:
      200:
        body: object

/profile:
  type: ProfileResource
  description: Краткий профиль пользователя - аватар, емейл и пр.
/bookmarks:
  type: BookmarksResource
  description: Сохранённые букмарки пользователя (туры, коллекции, поиск)
/orders/{order}:
  type: OrderResource
  description: Просмотр и редактирование заказа путешествия
/config:
  type: ConfigResource
  description: Конфигурация сайта - языки, валюта и т.д.
