#%RAML 1.0
title: Mitaba
version: v1
baseUri: ???
mediaType: application/json
types:
  Url: string
  Email: string

  Entry:
    properties:
      _uid: string
      start?: number
      stop?: number
      details?: string[]

  Profile:
    properties:
      _uid: string
      name?: string
      avatar?: Url
      email?: Email
      public_url?: Url

resourceTypes:
  EntriesResource:
    get:
      responses:
        200:
          body:
            properties:
              entries: Entry[]
        401:
          body: object
    post:
      body:
        properties:
          entries: Entry[]
      responses:
        200:
          body:
            properties:
              entries: Entry[]
        401:
          body: object
    put:
      body:
        properties:
          entries: Entry[]
      responses:
        200:
          body:
            properties:
              entries: Entry[]
        401:
          body: object
    delete:
      body:
        properties:
          entries: Entry[]
      responses:
        200:
          body: object

  ProfileResource:
    get:
      responses:
        200:
          body:
            properties:
              profile: Profile[]
        401:
          body: object

/entries:
  type: EntriesResource
/profile/{user_uid}:
  type: ProfileResource


