# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-09 12:52
from __future__ import unicode_literals

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Entry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start', models.DateTimeField()),
                ('stop', models.DateTimeField()),
                ('details', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=500), max_length=20, size=None)),
            ],
        ),
    ]
