# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-19 08:25
from __future__ import unicode_literals

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0002_entry_owner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entry',
            name='details',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=500), db_index=True, max_length=20, size=None),
        ),
    ]
